config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  devise_for :users
  root 'welcome#index'

  resources :articles
=begin RESTful
  get "/articles" index
  post "/articles" create
  delete "/articles/:id" destroy
  get "/articles/:id" show
  get "/articles/new" new
  get "/articles/:id/edit" edit
  patch "/articles/id" update
  put "/articles/id" updtate
=end



  #get 'special', to: "welcome#index"

  
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user	
  validates :title, presence: true
  validates :body, presence: true, length: {minimum: 20}
  before_save :set_visits_count

  def update_visits_count
    self.update(visits_count: self.visits_count + 1)
  end

  private


  def set_visits_count
    self.visits_count ||= 0
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	#before_action :validate_user, except: [:show, :index]
	before_action :authenticate_user!, except: [:show,:index] # devise (callback) tiene por defecto este helper para ser usado en los controladores, en vez de lo anterior
	before_action :set_article, except: [:index, :new, :create] # Callback muy popular

	#GET /articles
	def index
		@articles = Article.all
	end
	#GET /articles/:id
	def show
	  @article.update_visits_count	
	end

	#GET /articles/new
	def new
      @article = Article.new
	end
	#POST /articles
	def create
		@article = current_user.articles.new(articles_params)		
		if @article.save
		  redirect_to @article
		else
		  render :new
		end    
	end

	#GET /articles/:id/edit
	def edit

	end

	#PUT /articles/:id
	def update	  
	  if @article.update(articles_params)
	    redirect_to @article	
	  else
	  	render :edit
	  end	
	end

	#DELETE /articles/:id
	def destroy
		@article.destroy # elimina objeto de la BD
		redirect_to articles_path # index	
	end

	private

	#def validate_user
	#	redirect_to new_user_session_path, notice: "Necesitas iniciar sesión"
	#end

	def set_article
      @article = Article.find(params[:id])
	
	end

	def articles_params # nombre por convecion
	  params.require(:article).permit(:title,:body)	# objeto params, aqui no es permitido visit_counts. El nivel mas alto es el article
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<% name ||= "Editar "%>

<h1><%= name %> articulo</h1>

<%= form_for(@article) do |f| %>
  <% @article.errors.full_messages.each do |message| %>
    <div class="be-red white">
    	<%= message %>
    </div>

  <%end%>  
  <div class="field" >
  	<%= f.text_field :title, placehoder: "Titulo", class: "form-control" %>
  </div>
  <div class="field" >
  	<%= f.text_area :body, placehoder: "Escribe aqui un comentario", style:"height:250px;", class: "form-control" %>
  </div>
  <div class="field" >
  	<%= f.submit "Guardar", class: "btn be-red white" %>
  </div>

<%end%>

app/views/articles/edit.html.erb
<div style="width: 80%; margin: 0 auto;" >

<%= render "form" %>

</div>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
	<h1><%= link_to article.title, article %></h1>
	<div><%= article.body %> - <%= link_to "Eliminar", article, method: :delete, class: "red" %></div>
<%end%>

app/views/articles/new.html.erb
<div style="width: 80%; margin: 0 auto;" >

<h1>Crear articulo</h1>
<%= form_for(@article) do |f| %>
  <div class="field" >
  	<%= f.text_field :title, placehoder: "Titulo", class: "form-control" %>
  </div>
  <div class="field" >
  	<%= f.text_area :body, placehoder: "Escribe aqui un comentario", style:"height:250px;", class: "form-control" %>
  </div>
  <div class="field" >
  	<%= f.submit "Guardar", class: "btn be-red white" %>
  </div>

<%end%>

</div>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>	
<% unless @article.user.nil? %>
<p>Escrito por: <%= @article.user.email %> </p>

<%end%>
<p>Visitas: <%= @article.visits_count %> </p>

<div><%= @article.body %>-<%= link_to "Editar", edit_article_path(@article) %></div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :article_id %><br>
    <%= f.text_field :article_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Article</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.article %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render "/partials/navigation" %>  
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/partials/_navigation.html.erb
<header>
  	<nav class='be-red white large-padding'>
  		<ul class="no-list row center-xs">
  		  <li class="col-md" >
  		  	<%= link_to 'Inicio', root_path %>
  		  </li>
  		  <li class="col-md" >
  		  	Diseno
  		  </li>
  		  <li class="col-md" >
  		  	Programacion
  		  </li>
  		  <li class="col-md" >
  		  	Tecnologia
  		  </li>
        <% if user_signed_in? %> <!--Devise nos provee con algunos metodos-->
          <li class="col-md">
           <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete %>
          </li>
        <%else%>
          <li class="col-md">
           <%= link_to "Iniciar sesion", new_user_session_path %> <!--No es necesario poner el metodo GET-->
          </li>
          <li class="col-md">
           <%= link_to "Crear cuenta", new_user_registration_path %>
          </li>
          
        <%end%>
  			
  		</ul>
  	</nav>
</header>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
  <h1>Bienvenidos <%= current_user.email %></h1><!--Metodo current_user -->
<%end%>